#!/usr/bin/env python
'''
This file is part of the Python EJTP library.

The Python EJTP library is free software: you can redistribute it 
and/or modify it under the terms of the GNU Lesser Public License as
published by the Free Software Foundation, either version 3 of the 
License, or (at your option) any later version.

the Python EJTP library is distributed in the hope that it will be 
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser Public License for more details.

You should have received a copy of the GNU Lesser Public License
along with the Python EJTP library.  If not, see 
<http://www.gnu.org/licenses/>.
'''

__doc__ = '''ejtpd

This utility runs as a daemon, allowing a priveleged EJTP client to add
and remove client services from the process.

Usage:
    ejtpd launch [-f <sourcefile>] [-i <interface>]
    ejtpd client launch
    ejtpd client destroy
    ejtpd -h | --help
    ejtpd --version

Options:
    -f <sourcefile>    Specify the source JSON file for all configuration parameters
    -i <interface>     Specify client interface
    -c <crypto>        Literal encryptor cache
    -F <filter>        Filter regex (for ejtpd DaemonClient)
    -C <controller>    Controller interface
    -j                 Make a jack for this client
    -J                 Don't make a jack for this client
    -h --help          Show this help message
'''

from ejtp.vendor.docopt import docopt

if __name__ == '__main__':
    arguments = docopt(__doc__, version='ejtpd 0.9.0')
    print(arguments)
