#!/usr/bin/env python
'''
This file is part of the Python EJTP library.

The Python EJTP library is free software: you can redistribute it 
and/or modify it under the terms of the GNU Lesser Public License as
published by the Free Software Foundation, either version 3 of the 
License, or (at your option) any later version.

the Python EJTP library is distributed in the hope that it will be 
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser Public License for more details.

You should have received a copy of the GNU Lesser Public License
along with the Python EJTP library.  If not, see 
<http://www.gnu.org/licenses/>.
'''

__doc__ = '''ejtp-crypto

A simple little script for run EJTP encryptors from the command line.

Usage:
    ejtp-crypto ( encode | decode | sign | sig-verify ) ( id | with ) <parameter>
    ejtp-crypto -h | --help
    ejtp-crypto --version

Options:
    -h --help       Show this help message
'''

import sys

from ejtp.vendor.docopt import docopt
from ejtp.identity.cache import IdentityCache
from ejtp.config import configure_identity_cache

cache = IdentityCache()
configure_identity_cache(cache)

if __name__ == '__main__':
    arguments = docopt(__doc__, version='ejtp-crypto 0.9.2')

    input_text = sys.stdin.read().rstrip('\n')

    identity = None
    if arguments['id']:
        identity = cache.find_by_name(arguments['<parameter>'])

    if arguments['encode']:
        print(identity.encryptor.encrypt(input_text).export())
    if arguments['decode']:
        print(identity.encryptor.decrypt(input_text).export())
