#!/usr/bin/env python
'''
This file is part of the Python EJTP library.

The Python EJTP library is free software: you can redistribute it 
and/or modify it under the terms of the GNU Lesser Public License as
published by the Free Software Foundation, either version 3 of the 
License, or (at your option) any later version.

the Python EJTP library is distributed in the hope that it will be 
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser Public License for more details.

You should have received a copy of the GNU Lesser Public License
along with the Python EJTP library.  If not, see 
<http://www.gnu.org/licenses/>.
'''

__doc__ = '''ejtp-crypto

A simple little script for run EJTP encryptors from the command line.

Usage:
    ejtp-crypto ( encode | decode | sign | sig-verify ) ( id | with ) <parameter>
    ejtp-crypto -h | --help
    ejtp-crypto --version

Options:
    -h --help       Show this help message
'''

from ejtp.vendor.docopt import docopt

if __name__ == '__main__':
    arguments = docopt(__doc__, version='ejtp-crypto 0.9.2')
